eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
okta:
  oauth2:
    issuer: https://dev-57966697.okta.com/oauth2/default
    audience: api://default
    
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
      
